RK-312 : Implementing backlink and caching
hmrc/tax-fraud-reporting-frontend pull request #14
Opened 2021-12-12 23:23 UTC by shinealex33

RK-312 : Implementing backlink and caching

2021-12-13 15:48 UTC, ModisAtHMRC commented
Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]:
```
        saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
          case true => fraudReportDetails
          // $COVERAGE-OFF$Loggers
          case false => throw new IllegalStateException("Not able to create cache in Mongo")
          // $COVERAGE-ON
        }
```
The function `saveFraudReportDetails` has this implementation:
```
  def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
    createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
```
It always maps to true, so it appears the case false match is redundant, unless we need to change the implementation to reflect the success status of the operation.

The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.

I am searching for docs to confirm this but believe this is the value we need to be extracting withing the `map`.

2021-12-13 15:58 UTC, ModisAtHMRC commented
In `SessionCache.scala`, the function
```
  def isCachePresent(sessionId: String): Future[Boolean] = findById(sessionId).map {
    case Some(Cache(_, Some(data), _, _)) => true;
    case _                                => false;
  }
```
can be shortened to
```
  def isCachePresent(sessionId: String): Future[Boolean] = findById(sessionId) map {
    _ exists { cache => cache.data.isDefined }
  }
```.

2021-12-13 16:09 UTC, ModisAtHMRC commented
In `ActivityTypeController.scala`, the method `onPageLoad` can be made a little more readable from
```scala
 Action.async {
    implicit request =>
      sessionCache.isCacheNotPresentCreateOne(hc.sessionId.get.value) flatMap {
        case fraudReport if fraudReport.activityType.isDefined =>
          Future.successful(
            Ok(activityTypeView(form.fill(ActivityTypeViewModel(fraudReport.activityType.get)), onSubmitActivityType()))
          )
        case _ => Future.successful(Ok(activityTypeView(form, onSubmitActivityType())))

      }
  }
```
to
```scala
 Action.async {
    implicit request =>
      Future.successful {
        Ok {
          sessionCache.isCacheNotPresentCreateOne(hc.sessionId.get.value) flatMap { fraudReport =>
            val filledForm = fraudReport.activityType map {
              form.fill( ActivityTypeViewModel( _ )
            } getOrElse form

            activityTypeView( filledForm, onSubmitActivityType() )
          }
        }
      }
  }
```

2021-12-13 16:14 UTC, ModisAtHMRC commented
`UserAnswersCacheSpec.scala` appears to have redundant imports of `TimeUnit`.

2021-12-13 16:18 UTC, ModisAtHMRC commented
`ActivityTypeControllerSpec.scala` appears to have a redundant `SessionId` important.

2021-12-13 22:42 UTC, shinealex33 commented
> In `SessionCache.scala`, the function
> 
> ```scala
>   def isCachePresent(sessionId: String): Future[Boolean] = findById(sessionId).map {
>     case Some(Cache(_, Some(data), _, _)) => true;
>     case _                                => false;
>   }
> ```
> 
> can be shortened to
> 
> ```scala
>   def isCachePresent(sessionId: String): Future[Boolean] = findById(sessionId) map {
>     _ exists { cache => cache.data.isDefined }
>   }
> ```

2021-12-13 22:49 UTC, shinealex33 commented
> 

resolved. Please take 

> Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> 
> ```scala
>         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
>           case true => fraudReportDetails
>           // $COVERAGE-OFF$Loggers
>           case false => throw new IllegalStateException("Not able to create cache in Mongo")
>           // $COVERAGE-ON
>         }
> ```
> 
> The function `saveFraudReportDetails` has this implementation:
> 
> ```scala
>   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
>     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> ```
> 
> It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> 
> The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> 
> I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.



> Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> 
> ```scala
>         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
>           case true => fraudReportDetails
>           // $COVERAGE-OFF$Loggers
>           case false => throw new IllegalStateException("Not able to create cache in Mongo")
>           // $COVERAGE-ON
>         }
> ```
> 
> The function `saveFraudReportDetails` has this implementation:
> 
> ```scala
>   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
>     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> ```
> 
> It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> 
> The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> 
> I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.

Fixed the issue - please fix it.

2021-12-13 22:50 UTC, shinealex33 commented
> 

Fixed issue - please take a look

2021-12-13 22:50 UTC, shinealex33 commented
> > 
> 
> resolved. Please take
> 
> > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > ```scala
> >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> >           case true => fraudReportDetails
> >           // $COVERAGE-OFF$Loggers
> >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> >           // $COVERAGE-ON
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function `saveFraudReportDetails` has this implementation:
> > ```scala
> >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> 
> > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > ```scala
> >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> >           case true => fraudReportDetails
> >           // $COVERAGE-OFF$Loggers
> >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> >           // $COVERAGE-ON
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function `saveFraudReportDetails` has this implementation:
> > ```scala
> >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> 
> Fixed the issue - please fix it.

Fixed issue - please take a look

2021-12-13 22:50 UTC, shinealex33 commented
> > > 
> > 
> > 
> > resolved. Please take
> > > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > > ```scala
> > >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> > >           case true => fraudReportDetails
> > >           // $COVERAGE-OFF$Loggers
> > >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> > >           // $COVERAGE-ON
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The function `saveFraudReportDetails` has this implementation:
> > > ```scala
> > >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> > >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> > 
> > 
> > > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > > ```scala
> > >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> > >           case true => fraudReportDetails
> > >           // $COVERAGE-OFF$Loggers
> > >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> > >           // $COVERAGE-ON
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The function `saveFraudReportDetails` has this implementation:
> > > ```scala
> > >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> > >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> > 
> > 
> 
> Fixed issue - please take a look

2021-12-13 22:51 UTC, shinealex33 commented
> > 
> 
> resolved. Please take
> 
> > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > ```scala
> >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> >           case true => fraudReportDetails
> >           // $COVERAGE-OFF$Loggers
> >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> >           // $COVERAGE-ON
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function `saveFraudReportDetails` has this implementation:
> > ```scala
> >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> 
> > Within the function `isCacheNotPresentCreateOne` in `SessionCache.scala`, we have the following block processing a `Future[Boolean]`:
> > ```scala
> >         saveFraudReportDetails(FraudReportDetails(None)) flatMap { 
> >           case true => fraudReportDetails
> >           // $COVERAGE-OFF$Loggers
> >           case false => throw new IllegalStateException("Not able to create cache in Mongo")
> >           // $COVERAGE-ON
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function `saveFraudReportDetails` has this implementation:
> > ```scala
> >   def saveFraudReportDetails(rdh: FraudReportDetails)(implicit hc: HeaderCarrier): Future[Boolean] =
> >     createOrUpdate(sessionId, fraudReportDetailsKey, Json.toJson(rdh)) map (_ => true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It always maps to `true`, so the `case false` match appears redundant, unless we need to change the implementation to reflect the success status of the operation.
> > The function it uses, `createOrUpdate`, returns a `Future` containing a `DataBaseUpdate[A],` which appears to log the outcome of the operation within the property `writeResult: LastError`, which in turn has a field `ok: Boolean` that I assume tells us whether the DB op succeeded or not.
> > I am searching for docs to confirm this but believe this is the value we need to be extracting within the `map`.
> 
> Fixed the issue - please fix it.

2021-12-14 10:07 UTC, ModisAtHMRC requested changes
Overall good code which can just be shortened a little by removing some redundant instances of `Future.successful`.

2021-12-14 10:07 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/ActivityTypeController.scala
>    }
The `flatMap` of a `Future.succecssful` can be simplified to a `map`:
```scala
  def onSubmit(): Action[AnyContent] = Action.async {
   import uk.gov.hmrc.taxfraudreportingfrontend.controllers.routes

    implicit request =>
      form.bindFromRequest().fold(
        formWithErrors => Future.successful(
          BadRequest( activityTypeView( formWithErrors, onSubmitActivityType() ) )
        ),
        activityType =>
          userAnswersCache.cacheActivityType(activityType.activityType) map (
            _ => Redirect( routes.ReportingTypeController.onPageLoad() )
          )
      )
  }
```

2021-12-14 10:07 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/IndexViewController.scala
>    }
The async function can be simplified to a synchronous one:
```scala
  def onPageLoad(): Action[AnyContent] = Action { implicit request =>
    val response = Ok( indexView() )
    
    if ( request.session.data contains SessionKeys.sessionId ) response
    else response.addingToSession(SessionKeys.sessionId -> UUID.randomUUID.toString)
  }
```

2021-12-14 10:25 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/ActivityTypeController.scala
>    }
implemented thanks!

2021-12-14 10:25 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/IndexViewController.scala
>    }
implemented thanks!

2021-12-14 10:30 UTC, ModisAtHMRC approved these changes
Awesome, futures all sorted. Happy to approve.

2021-12-14 10:30 UTC, merged