RK-229 Build Person Connection Type Page
hmrc/tax-fraud-reporting-frontend pull request #28
Opened 2022-01-17 16:32 UTC by shiromi

2022-01-18 08:46 UTC, wolfendale commented
Would be good if we had separate commits for different pages, would make it easier to track changes :)

2022-01-18 08:46 UTC, wolfendale requested changes

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  case object partner            extends PersonConnectionType
These should all be title cased

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
Does this belong here?

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +            form.value.head.asInstanceOf[ConnectionType].personConnectionType == value,
If we need to use `form.value` and get a specific type, we should make sure to pass the type explicitly `form: Form[WhateverType]` so that we don't need to cast it.

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +          if (value.toString.equals("other"))
Shouldn't compare strings when you have strictly typed values `value == other`

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +        content = Text(messages(s"selectConnection.${value.toString}")),
Should we be wrapping content in `messages(...)` here? I would have thought that this is done in the end components. If we can avoid that we can also remove the implicit `Messages` parameter

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +                    if (form("otherConnection").hasErrors)
Multiline `if` expressions should have braces

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCacheSpec.scala
> +      Await.result(testCache.cacheConnection(Some(mockPersonConnection))(getRequest), Duration.Inf)
Mix in the `ScalaFutures` trait into this file and use `.futureValue` instead of `Await.result(...)`

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCacheSpec.scala
> +  private val mockPersonConnection = ConnectionType(PersonConnectionType.values.head, Option("otherConnection"))
This data would be invalid as it would be `Partner` with input for `Other`

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCacheSpec.scala
> +      verify(mockSessionCache).saveFraudReportDetails(requestCaptor.capture())(ArgumentMatchers.eq(getRequest))
Does `verify(...)` actually do anything here?

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCacheSpec.scala
> +      testCacheData shouldBe None
Why do we have this assertion here? I don't think this tells us anything about this particular test case

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCacheSpec.scala
> +    "get person connect type data from cache" in {
We need another test to show that when the person connection details exist that they are passed through to here

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/controllers/PersonConnectionTypeControllerSpec.scala
> +      redirectLocation(result).value mustEqual "/report-tax-fraud/select-connection"
Should use the reverse route for this so that if the url changes the test doesn't break

2022-01-18 08:46 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreportingfrontend/controllers/forms/PersonConnectionTypeProviderSpec.scala
> +    behave like mandatoryField(form, fieldName, requiredError = FormError(fieldName, requiredKey))
Need tests to show that more input is required if you select "Other"

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCache.scala
> +  def getConnection()(implicit request: Request[_]): Future[Option[ConnectionType]] =
This is never used, what is it for?

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/PersonConnectionTypeController.scala
> +          case Some(f) if f.connectionType.nonEmpty => form.fill(f.connectionType.get)
We should never use `.get` on `Option`s

2022-01-18 08:46 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/PersonConnectionTypeController.scala
> +  private def onSubmitConnection() = routes.PersonConnectionTypeController.onSubmit()
This can just be referenced in the view instead of passed in

2022-01-18 08:57 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
Yeah, I also can't help suspect that this could be generalised for other enums too, such as `ReportingType` and how long has the fraud been going on.

2022-01-18 09:02 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/PersonConnectionTypeController.scala
> +          case Some(f) if f.connectionType.nonEmpty => form.fill(f.connectionType.get)
@wolfendale, isn't this only the case when one hasn't previously checked that the `Option` is defined? Or do we want to avoid it strictly as a matter of habit and convention?

2022-01-18 09:04 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
I meant more that it should potentially be in the view. I think that without "Other" it could be generalised.

2022-01-18 09:05 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCache.scala
> +  def getConnection()(implicit request: Request[_]): Future[Option[ConnectionType]] =
In the controller we use the session cache instead. They seem to do the same thing?

2022-01-18 09:06 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/controllers/PersonConnectionTypeController.scala
> +          case Some(f) if f.connectionType.nonEmpty => form.fill(f.connectionType.get)
We should always avoid it as a convention. The number of errors that I've seen creep into services because someone thought it was safe to use `.get` is innumerable. Also, even if this is safe now, someone could subtly change the line without realising and make it unsafe, that's another thing that I've seen happen a million times!

2022-01-18 09:08 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
Ah, I see. Did not consider the text input.

2022-01-18 09:10 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCache.scala
> +  def getConnection()(implicit request: Request[_]): Future[Option[ConnectionType]] =
Need to check but I suspect the `SessionCache` uses this method since it depends on `UserAnswersCache`.

2022-01-18 09:14 UTC, shiromi commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
this is easy is handle in here instead of adding to the view, we have 14 options and last option has conditional revealing content.

2022-01-18 12:57 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  )
@wolfendale, could we eliminate the need to write out the `Seq` of values by writing the following?
```scala
object PersonConnectionType extends Enumeration {
  val
    Partner,
    FamilyMember,
    BusinessPartner,
    Employer,
    ExEmployer,
    Employee,
    Colleague,
    Friend,
    Neighbour,
    Customer,
    BusinessCompetitor,
    Other = Value

  private val govukErrorMessage: GovukErrorMessage = new GovukErrorMessage()
  private val govukHint: GovukHint                 = new GovukHint()
  private val govukLabel: GovukLabel               = new GovukLabel()
}
```

2022-01-18 15:02 UTC, shiromi commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  def options(form: Form[_])(implicit messages: Messages): Seq[RadioItem] = values.map {
move to the view

2022-01-18 15:04 UTC, shiromi commented on app/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCache.scala
> +  def getConnection()(implicit request: Request[_]): Future[Option[ConnectionType]] =
haven't done the changes

2022-01-18 15:15 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +sealed trait PersonConnectionType
I would do this:
```scala
sealed abstract class PersonConnectionType(toString: String) extends WithName(toString)
```
and then...

2022-01-18 15:15 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  case object Partner            extends WithName("partner") with PersonConnectionType
...shorten all these lines to something like
```scala
case object Partner extends PersonConnectionType("partner")
```

2022-01-18 15:22 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/cache/UserAnswersCache.scala
> +  def getConnection()(implicit request: Request[_]): Future[Option[ConnectionType]] =
Going to talk about this more holistically when Shine is back

2022-01-18 15:23 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreportingfrontend/models/PersonConnectionType.scala
> +  )
In theory yes but the `Enumerable` stuff gives us some extra stuff.

2022-01-19 08:55 UTC, wolfendale approved these changes

2022-01-19 09:00 UTC, merged