build business name front end
hmrc/tax-fraud-reporting-frontend pull request #35
Opened 2022-01-24 15:25 UTC by shiromi

2022-01-24 17:38 UTC, ModisAtHMRC requested changes
In addition to the 3 suggested changes, we can also convert the definition of `Mode.jsLiteral` to the Single Abstract Method `_.toString`.

2022-01-24 17:38 UTC, ModisAtHMRC commented on migrations/applied_migrations/BusinessName.sh
> +echo "Migration BusinessName completed"
Is this a generated file? Feels like it and, if so, perhaps it need not be versioned?

2022-01-24 17:38 UTC, ModisAtHMRC commented on test/controllers/BusinessNameControllerSpec.scala
> +  def onwardRoute = Call("GET", "/foo")
This can be made a `val`.

2022-01-24 17:38 UTC, ModisAtHMRC commented on test/controllers/BusinessNameControllerSpec.scala
> +  lazy val businessNameRoute = routes.BusinessNameController.onPageLoad(Index(0), NormalMode).url
The previous 4 `val`s can all be made `private`.

2022-01-25 08:15 UTC, shiromi commented on migrations/applied_migrations/BusinessName.sh
> +echo "Migration BusinessName completed"
this is auto generated file

2022-01-26 11:10 UTC, wolfendale requested changes

2022-01-26 11:10 UTC, wolfendale commented on conf/app.routes
> +GET        /using-this-service                          controllers.IndexController.onPageLoad
We should put this back to `/`. it's included twice in the routes so that both `/` and `/using-this-service` both go to the first page :)

2022-01-26 11:13 UTC, wolfendale approved these changes

2022-01-26 14:14 UTC, ModisAtHMRC approved these changes

2022-01-26 14:17 UTC, merged