RK-286 added back link, cookie concent, language toggle and tech supp…
hmrc/tax-fraud-reporting-frontend pull request #7
Opened 2021-11-23 14:43 UTC by shiromi

…ort feature on template

2021-11-24 16:51 UTC, shinealex33 requested changes
please fix the review comments

2021-11-24 16:51 UTC, shinealex33 commented on test/uk/gov/hmrc/taxfraudreportingfrontend/controllers/ViewUtilsSpec.scala
> +    /*
Please remove the commented code if it is not required.

2021-11-24 16:51 UTC, shinealex33 commented on project/plugins.sbt
> +addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.4")
add end of the line

2021-11-24 16:51 UTC, shinealex33 commented on conf/messages
> +error.summary.title = There is a problem
add end of the line

2021-11-24 16:51 UTC, shinealex33 commented on conf/app.routes
> +GET        /helloWorld                                   @uk.gov.hmrc.taxfraudreportingfrontend.controllers.HelloWorldController.helloWorld
please add end of the line

2021-11-24 16:51 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/components/error_summary.scala.html
> +}
please add end of the line

2021-11-24 16:51 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/components/errorSummary.scala.html
> +}
please add end of the line

2021-11-24 16:51 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/ViewUtils.scala
> +  def errorPrefix(form: Form[_])(implicit messages: Messages): String =
How do we handle the error Title. We don't want to merge the commented code into main

2021-11-24 16:51 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/ViewUtils.scala
> +  /*
why we commented this piece of this code

2021-11-24 16:51 UTC, shinealex33 commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/LanguageSelect.scala.html
> +))
add end of the file

2021-11-24 16:59 UTC, shiromi commented on app/uk/gov/hmrc/taxfraudreportingfrontend/views/ViewUtils.scala
> +  def errorPrefix(form: Form[_])(implicit messages: Messages): String =
once we add the error will add the code back. for now I have removed the commented lines.

2021-11-25 09:59 UTC, shinealex33 approved these changes
LGTM

2021-11-25 09:59 UTC, merged